CREATE OR ALTER PROCEDURE ARTICULOS_ALMACEN RETURNS (
	ARTICULO_ID INTEGER,
	NOMBRE_ARTICULO VARCHAR(200),
	CODIGO_ARTICULO VARCHAR(20),
	CLAVE_ARTICULO VARCHAR(20),
	ALMACEN_ID INTEGER,
	NOMBRE_ALMACEN VARCHAR(50),
	EXISTENCIA INTEGER
)
AS
DECLARE VARIABLE ROL_CLAVE_ART_ID INTEGER;
DECLARE VARIABLE NOMBRE_ROL VARCHAR(50);
DECLARE VARIABLE CLAVE_ARTICULO_GENERICO VARCHAR(20);

begin
    FOR SELECT A.ARTICULO_ID, A.NOMBRE FROM ARTICULOS A    
		WHERE A.ESTATUS IN ('A','C')
		ORDER BY A.ARTICULO_ID
    INTO :ARTICULO_ID, :NOMBRE_ARTICULO DO
    BEGIN			    
		    
		FOR SELECT RCA.ROL_CLAVE_ART_ID, RCA.NOMBRE, CA.CLAVE_ARTICULO FROM CLAVES_ARTICULOS CA
			INNER JOIN ROLES_CLAVES_ARTICULOS RCA ON RCA.ROL_CLAVE_ART_ID=CA.ROL_CLAVE_ART_ID
			WHERE CA.ARTICULO_ID = :ARTICULO_ID AND RCA.ROL_CLAVE_ART_ID IN (17,18)
			ORDER BY RCA.ROL_CLAVE_ART_ID
		INTO :ROL_CLAVE_ART_ID, :NOMBRE_ROL, :CLAVE_ARTICULO_GENERICO DO
		BEGIN
			IF (:ROL_CLAVE_ART_ID = 17) THEN
				CODIGO_ARTICULO = :CLAVE_ARTICULO_GENERICO;
			ELSE IF (:ROL_CLAVE_ART_ID = 18) THEN
				CLAVE_ARTICULO = :CLAVE_ARTICULO_GENERICO;
		END
							
		FOR SELECT EA.ALMACEN_ID, A.NOMBRE, EA.EXISTENCIA  FROM EXIVAL_ALMS_ART(:ARTICULO_ID, current_date, 'S') EA
		INNER JOIN ALMACENES A ON A.ALMACEN_ID=EA.ALMACEN_ID
		INTO :ALMACEN_ID, :NOMBRE_ALMACEN, :EXISTENCIA DO
		BEGIN
			SUSPEND;
		END
    END
END