CREATE OR ALTER PROCEDURE CLIENTES_POLITICAS (PRECIO_EMPRESA_ID INTEGER, VENDEDOR_ID_IN INTEGER)
RETURNS (
	CLIENTE_ID INTEGER,
	CLAVE_CLIENTE VARCHAR(20), 
	NOMBRE_CLIENTE VARCHAR(200),
    TIPO_CLIENTE_ID INTEGER, 
    TIPO_CLIENTE_NOMBRE VARCHAR(50),
    ZONA_CLIENTE_ID INTEGER, 
    ZONA_CLIENTE_NOMBRE VARCHAR(50),
    COBRADOR_ID INTEGER,
    COBRADOR_NOMBRE VARCHAR(100),
    VENDEDOR_ID INTEGER,
    VENDEDOR_NOMBRE VARCHAR(100),
    DIR_CLI_ID INTEGER, 
    RFC_CURP VARCHAR(18), 
    CALLE VARCHAR(430),
    NUM_EXTERIOR VARCHAR(10), 
    NUM_INTERIOR VARCHAR(10),
    COLONIA VARCHAR(100), 
    POBLACION VARCHAR(100),
    CODIGO_POSTAL VARCHAR(10),
    TELEFONO1 VARCHAR(35),
    TELEFONO2 VARCHAR(35), 
    DESCUENTO DOUBLE PRECISION, 
    POLITICA_DSCTO_ART_CLI_ID INTEGER, 
    NOMBRE VARCHAR(50),  
    LIMITE_CREDITO DOUBLE PRECISION
)
AS
/*declare variable PRECIO_LISTA_ID integer;*/

BEGIN  	
	IF (VENDEDOR_ID_IN = 0) THEN
	BEGIN
		FOR SELECT C.CLIENTE_ID, CC.CLAVE_CLIENTE, C.NOMBRE AS NOMBRE_CLIENTE, 
		C.TIPO_CLIENTE_ID, TC.NOMBRE AS TIPO_CLIENTE_NOMBRE, 
		C.ZONA_CLIENTE_ID, ZC.NOMBRE AS ZONA_CLIENTE_NOMBRE, 
		C.COBRADOR_ID, 
		CB.NOMBRE AS COBRADOR_NOMBRE, 
		C.VENDEDOR_ID, 
		V.NOMBRE AS VENDEDOR_NOMBRE, 
		DC.DIR_CLI_ID, DC.RFC_CURP, DC.CALLE, DC.NUM_EXTERIOR, DC.NUM_INTERIOR, DC.COLONIA, DC.POBLACION, DC.CODIGO_POSTAL, DC.TELEFONO1, DC.TELEFONO2 
		,PDAC.DESCUENTO, PDAC.POLITICA_DSCTO_ART_CLI_ID, PDAC.NOMBRE, C.LIMITE_CREDITO 
		FROM CLIENTES C 
		INNER JOIN DIRS_CLIENTES DC ON DC.CLIENTE_ID=C.CLIENTE_ID 
		INNER JOIN TIPOS_CLIENTES TC ON TC.TIPO_CLIENTE_ID=C.TIPO_CLIENTE_ID 
		INNER JOIN ZONAS_CLIENTES ZC ON ZC.ZONA_CLIENTE_ID=C.ZONA_CLIENTE_ID 
		INNER JOIN COBRADORES CB ON CB.COBRADOR_ID=C.COBRADOR_ID 
		INNER JOIN VENDEDORES V ON V.VENDEDOR_ID=C.VENDEDOR_ID 
		INNER JOIN CLAVES_CLIENTES CC ON CC.CLIENTE_ID=C.CLIENTE_ID 
		LEFT JOIN PRECIOS_CLI_CLI PCC ON PCC.CLIENTE_ID=C.CLIENTE_ID AND PCC.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID
		LEFT JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON PDAC.POLITICA_DSCTO_ART_CLI_ID = PCC.POLITICA_DSCTO_ART_CLI_ID 
		WHERE C.ESTATUS IN (SELECT ESTATUS FROM CONFIGURACION_CLIENTES) --AND C.VENDEDOR_ID = :VENDEDOR_ID_IN
		AND DC.NOMBRE_CONSIG LIKE '%principal%'
	    INTO :CLIENTE_ID, :CLAVE_CLIENTE, :NOMBRE_CLIENTE, :TIPO_CLIENTE_ID, :TIPO_CLIENTE_NOMBRE, :ZONA_CLIENTE_ID, :ZONA_CLIENTE_NOMBRE,
    		:COBRADOR_ID, :COBRADOR_NOMBRE, :VENDEDOR_ID, :VENDEDOR_NOMBRE, :DIR_CLI_ID, :RFC_CURP, :CALLE, :NUM_EXTERIOR, :NUM_INTERIOR,
    		:COLONIA, :POBLACION, :CODIGO_POSTAL, :TELEFONO1, :TELEFONO2, :DESCUENTO, :POLITICA_DSCTO_ART_CLI_ID, :NOMBRE, :LIMITE_CREDITO
	  	DO
	  	BEGIN
		  	:DESCUENTO = 0.00;
		  	SELECT CASE PCT.POLITICA_DSCTO_ART_CLI_ID WHEN NULL THEN 0 ELSE PCT.POLITICA_DSCTO_ART_CLI_ID END AS POLITICA_DSCTO_ART_CLI_ID, PDAC.NOMBRE 
			FROM PRECIOS_CLI_TIPO PCT 
			INNER JOIN POLITICAS_PRECIOS_CLIENTES PPC ON PPC.POLITICA_PRECIOS_CLI_ID = PCT.POLITICA_PRECIOS_CLI_ID 
			INNER JOIN TIPOS_CLIENTES TC ON TC.TIPO_CLIENTE_ID = PCT.TIPO_CLIENTE_ID 
			INNER JOIN PRECIOS_EMPRESA PE ON PE.PRECIO_EMPRESA_ID = PCT.PRECIO_EMPRESA_ID 
			INNER JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON PDAC.POLITICA_DSCTO_ART_CLI_ID = PCT.POLITICA_DSCTO_ART_CLI_ID 
			WHERE PDAC.ES_DSCTO_EXCLUSIVO = 'S' AND PPC.HABILITADA = 'S' AND PE.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID AND TC.TIPO_CLIENTE_ID = :TIPO_CLIENTE_ID
			INTO :POLITICA_DSCTO_ART_CLI_ID, :NOMBRE;
	  	SUSPEND;	
	  	END
  	END ELSE BEGIN
	  	FOR SELECT C.CLIENTE_ID, CC.CLAVE_CLIENTE, C.NOMBRE AS NOMBRE_CLIENTE, 
		C.TIPO_CLIENTE_ID, TC.NOMBRE AS TIPO_CLIENTE_NOMBRE, 
		C.ZONA_CLIENTE_ID, ZC.NOMBRE AS ZONA_CLIENTE_NOMBRE, 
		C.COBRADOR_ID, 
		CB.NOMBRE AS COBRADOR_NOMBRE, 
		C.VENDEDOR_ID, 
		V.NOMBRE AS VENDEDOR_NOMBRE, 
		DC.DIR_CLI_ID, DC.RFC_CURP, DC.CALLE, DC.NUM_EXTERIOR, DC.NUM_INTERIOR, DC.COLONIA, DC.POBLACION, DC.CODIGO_POSTAL, DC.TELEFONO1, DC.TELEFONO2 
		,PDAC.DESCUENTO, PDAC.POLITICA_DSCTO_ART_CLI_ID, PDAC.NOMBRE, C.LIMITE_CREDITO 
		FROM CLIENTES C 
		INNER JOIN DIRS_CLIENTES DC ON DC.CLIENTE_ID=C.CLIENTE_ID 
		INNER JOIN TIPOS_CLIENTES TC ON TC.TIPO_CLIENTE_ID=C.TIPO_CLIENTE_ID 
		INNER JOIN ZONAS_CLIENTES ZC ON ZC.ZONA_CLIENTE_ID=C.ZONA_CLIENTE_ID 
		INNER JOIN COBRADORES CB ON CB.COBRADOR_ID=C.COBRADOR_ID 
		INNER JOIN VENDEDORES V ON V.VENDEDOR_ID=C.VENDEDOR_ID 
		INNER JOIN CLAVES_CLIENTES CC ON CC.CLIENTE_ID=C.CLIENTE_ID 
		LEFT JOIN PRECIOS_CLI_CLI PCC ON PCC.CLIENTE_ID=C.CLIENTE_ID AND PCC.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID
		LEFT JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON PDAC.POLITICA_DSCTO_ART_CLI_ID = PCC.POLITICA_DSCTO_ART_CLI_ID 
		WHERE C.ESTATUS IN (SELECT ESTATUS FROM CONFIGURACION_CLIENTES) AND C.VENDEDOR_ID = :VENDEDOR_ID_IN
		AND DC.NOMBRE_CONSIG LIKE '%principal%'
	    INTO :CLIENTE_ID, :CLAVE_CLIENTE, :NOMBRE_CLIENTE, :TIPO_CLIENTE_ID, :TIPO_CLIENTE_NOMBRE, :ZONA_CLIENTE_ID, :ZONA_CLIENTE_NOMBRE,
    		:COBRADOR_ID, :COBRADOR_NOMBRE, :VENDEDOR_ID, :VENDEDOR_NOMBRE, :DIR_CLI_ID, :RFC_CURP, :CALLE, :NUM_EXTERIOR, :NUM_INTERIOR,
    		:COLONIA, :POBLACION, :CODIGO_POSTAL, :TELEFONO1, :TELEFONO2, :DESCUENTO, :POLITICA_DSCTO_ART_CLI_ID, :NOMBRE, :LIMITE_CREDITO
	  	DO
	  	BEGIN    
		  	:DESCUENTO = 0.00;
		  	SELECT CASE PCT.POLITICA_DSCTO_ART_CLI_ID WHEN NULL THEN 0 ELSE PCT.POLITICA_DSCTO_ART_CLI_ID END AS POLITICA_DSCTO_ART_CLI_ID, PDAC.NOMBRE 
			FROM PRECIOS_CLI_TIPO PCT 
			INNER JOIN POLITICAS_PRECIOS_CLIENTES PPC ON PPC.POLITICA_PRECIOS_CLI_ID = PCT.POLITICA_PRECIOS_CLI_ID 
			INNER JOIN TIPOS_CLIENTES TC ON TC.TIPO_CLIENTE_ID = PCT.TIPO_CLIENTE_ID 
			INNER JOIN PRECIOS_EMPRESA PE ON PE.PRECIO_EMPRESA_ID = PCT.PRECIO_EMPRESA_ID 
			INNER JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON PDAC.POLITICA_DSCTO_ART_CLI_ID = PCT.POLITICA_DSCTO_ART_CLI_ID 
			WHERE PDAC.ES_DSCTO_EXCLUSIVO = 'S' AND PPC.HABILITADA = 'S' AND PE.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID AND TC.TIPO_CLIENTE_ID = :TIPO_CLIENTE_ID
			INTO :POLITICA_DSCTO_ART_CLI_ID, :NOMBRE;
			
	  		SUSPEND;	
	  	END	
  	END
END