CREATE OR ALTER PROCEDURE ARTICULOS_MOBIL (FECHAINICIO DATE, FECHAFIN DATE)
RETURNS (
	ARTICULO_ID INTEGER,
	NOMBRE_ARTICULO VARCHAR(200),
	CODIGO_ARTICULO VARCHAR(20),
	CLAVE_ARTICULO VARCHAR(20),
	FACTOR_VENTA DOUBLE PRECISION,
	UNIDAD_VENTA VARCHAR(20),
	PORCENTAJE_IMPUESTO DOUBLE PRECISION,
	PRECIO DOUBLE PRECISION,
	DESCUENTO_PROMOCION DOUBLE PRECISION,
	PRECIO_NETO DOUBLE PRECISION,
	UNIDAD_MINIMA_VENTA DOUBLE PRECISION,
	PIEZAS_X_INNER DOUBLE PRECISION,
	PIEZAS_X_MASTER DOUBLE PRECISION,
	CODIGO_BARRAS VARCHAR(20),
	CODIGO_BARRAS_INNER VARCHAR(20),
	CODIGO_BARRAS_MASTER VARCHAR(20)
)
AS
DECLARE VARIABLE ROL_CLAVE_ART_ID INTEGER;
DECLARE VARIABLE NOMBRE_ROL VARCHAR(50);
DECLARE VARIABLE CLAVE_ARTICULO_GENERICO VARCHAR(20);
--VARIABLES TOMADAS DE LA CONFIGURACION
DECLARE VARIABLE PRECIO_EMPRESA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CLAVE_PRINCIPAL_ID INTEGER;
DECLARE VARIABLE ROL_ART_CLAVE_ALTERNA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_INNER_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_MASTER_ID INTEGER;

DECLARE VARIABLE APPLY_POLITICA_PRECIO_CLIENTES INTEGER;
DECLARE VARIABLE PORCENTAJE_DESC_PRECIO_CLIENTE DOUBLE PRECISION;
BEGIN
	SELECT PRECIO_EMPRESA_ID, ROL_ART_CLAVE_PRINCIPAL_ID, ROL_ART_CLAVE_ALTERNA_ID, ROL_ART_CODIGO_BARRA_ID, 
    ROL_ART_CODIGO_BARRA_INNER_ID, ROL_ART_CODIGO_BARRA_MASTER_ID, APPLY_POLITICA_PRECIO_CLIENTES FROM CONFIGURACION_MOBIL
    INTO :PRECIO_EMPRESA_ID, :ROL_ART_CLAVE_PRINCIPAL_ID, :ROL_ART_CLAVE_ALTERNA_ID, :ROL_ART_CODIGO_BARRA_ID, 
    :ROL_ART_CODIGO_BARRA_INNER_ID, :ROL_ART_CODIGO_BARRA_MASTER_ID, :APPLY_POLITICA_PRECIO_CLIENTES;
   	
   	IF (:APPLY_POLITICA_PRECIO_CLIENTES = 1)THEN
   	BEGIN
		SELECT PDAC.DESCUENTO
		FROM POLITICAS_PRECIOS_CLIENTES C
		INNER JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON C.politica_dscto_art_cli_id= PDAC.politica_dscto_art_cli_id		
		WHERE c.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID	
		INTO :PORCENTAJE_DESC_PRECIO_CLIENTE;
   	END

    FOR SELECT
        A.ARTICULO_ID, A.NOMBRE, A.FACTOR_VENTA, A.UNIDAD_VENTA
        ,I.PCTJE_IMPUESTO, PA.PRECIO, PA.PRECIO * (1 + (I.PCTJE_IMPUESTO / 100))
        FROM PRECIOS_EMPRESA PE
        INNER JOIN PRECIOS_ARTICULOS PA ON PA.PRECIO_EMPRESA_ID=PE.PRECIO_EMPRESA_ID
        INNER JOIN ARTICULOS A ON A.ARTICULO_ID=PA.ARTICULO_ID
        INNER JOIN IMPUESTOS_ARTICULOS IA ON IA.ARTICULO_ID=A.ARTICULO_ID
        INNER JOIN IMPUESTOS I ON IA.IMPUESTO_ID=I.IMPUESTO_ID                
        WHERE A.ESTATUS IN ('A','C') AND PE.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID
        ORDER BY A.ARTICULO_ID
    INTO :ARTICULO_ID, :NOMBRE_ARTICULO, :FACTOR_VENTA, :UNIDAD_VENTA, :PORCENTAJE_IMPUESTO, :PRECIO, :PRECIO_NETO DO
    BEGIN   
	    
	    IF (:APPLY_POLITICA_PRECIO_CLIENTES = 1)THEN
   		BEGIN	  
	   		IF (:PORCENTAJE_IMPUESTO <> 0)THEN
	   		BEGIN
	   			:PRECIO_NETO = (:PRECIO - (:PRECIO * (:PORCENTAJE_DESC_PRECIO_CLIENTE / 100))) * (1 + (:PORCENTAJE_IMPUESTO / 100));
	   			:PRECIO = :PRECIO / (1 + (:PORCENTAJE_IMPUESTO / 100));
	   		END
   		END
	    	    	 
	    
        -- PROMOCIONES
        DESCUENTO_PROMOCION= 0.00;
        SELECT DPA.DESCUENTO FROM POLITICAS_DSCTOS_PROMOCION PDP
        INNER JOIN DSCTOS_PROMO_ARTS DPA ON PDP.POLITICA_DSCTO_PROMO_ID = DPA.POLITICA_DSCTO_PROMO_ID        
        WHERE DPA.ARTICULO_ID=:ARTICULO_ID AND PDP.FECHA_INI_VIGENCIA>=:FECHAINICIO AND PDP.FECHA_FIN_VIGENCIA<=:FECHAFIN AND PDP.HABILITADA='S'
        INTO :DESCUENTO_PROMOCION;
    
        IF (:DESCUENTO_PROMOCION IS NOT NULL)THEN
            PRECIO_NETO = :PRECIO_NETO * ( 1 - (:DESCUENTO_PROMOCION/100));
        
                CODIGO_ARTICULO = 'SIN_CODIGO';
                CLAVE_ARTICULO = 'SIN_CLAVE';
                CODIGO_BARRAS = 'SIN_CODIGO_BARRAS';
                CODIGO_BARRAS_INNER = 'SIN_CODIGO_INNER';
                CODIGO_BARRAS_MASTER = 'SIN_CODIGO_MASTER';
        FOR SELECT RCA.ROL_CLAVE_ART_ID, RCA.NOMBRE, CA.CLAVE_ARTICULO FROM CLAVES_ARTICULOS CA
            INNER JOIN ROLES_CLAVES_ARTICULOS RCA ON RCA.ROL_CLAVE_ART_ID=CA.ROL_CLAVE_ART_ID            
            WHERE CA.ARTICULO_ID = :ARTICULO_ID AND RCA.ROL_CLAVE_ART_ID IN (:ROL_ART_CLAVE_PRINCIPAL_ID,:ROL_ART_CLAVE_ALTERNA_ID, :ROL_ART_CODIGO_BARRA_ID, :ROL_ART_CODIGO_BARRA_INNER_ID, :ROL_ART_CODIGO_BARRA_MASTER_ID)
            ORDER BY RCA.ROL_CLAVE_ART_ID
        INTO :ROL_CLAVE_ART_ID, :NOMBRE_ROL, :CLAVE_ARTICULO_GENERICO DO
        BEGIN
            IF (:ROL_CLAVE_ART_ID = :ROL_ART_CLAVE_PRINCIPAL_ID) THEN        
                    CODIGO_ARTICULO = :CLAVE_ARTICULO_GENERICO;        
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CLAVE_ALTERNA_ID) THEN
                CLAVE_ARTICULO = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_ID) THEN
                CODIGO_BARRAS = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_INNER_ID) THEN
                CODIGO_BARRAS_INNER = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_MASTER_ID) THEN
                CODIGO_BARRAS_MASTER = :CLAVE_ARTICULO_GENERICO;
        END
        
        SELECT UNI_MIN_VENTA, CANTIDAD_INNER, MASTER FROM LIBRES_ARTICULOS
        WHERE ARTICULO_ID = :ARTICULO_ID
        INTO :UNIDAD_MINIMA_VENTA, :PIEZAS_X_INNER, :PIEZAS_X_MASTER;    
        
        IF (:UNIDAD_MINIMA_VENTA IS NULL) THEN
            UNIDAD_MINIMA_VENTA = 0.00;
        IF (:PIEZAS_X_INNER IS NULL) THEN
            PIEZAS_X_INNER = 0.00;
        IF (:PIEZAS_X_MASTER IS NULL) THEN
            PIEZAS_X_MASTER = 0.00;
        
        SUSPEND;
    END
END