CREATE OR ALTER PROCEDURE CALCULA_EXISTENCIA_ARTICULO (V_ARTICULO_ID INTEGER, V_FECHA DATE)
RETURNS (
	ALMACEN_ID INTEGER,
	EXIS_UNID NUMERIC,
	EXIS_COSTO NUMERIC
)
AS
DECLARE VARIABLE EXIS_UNID_ALM NUMERIC(18,5);
DECLARE VARIABLE EXIS_COSTO_ALM NUMERIC(15,2);
BEGIN
  /* Calcular la existencia y el valor del artículo dado en todo almacén,
     a la fecha dada. */
  EXIS_UNID = 0;
  EXIS_COSTO = 0;
  FOR SELECT ALMACEN_ID
      FROM ALMACENES_ART(:V_ARTICULO_ID)
      INTO ALMACEN_ID
  DO
  BEGIN
    EXECUTE PROCEDURE CALC_EXIS_ARTALM V_ARTICULO_ID, ALMACEN_ID, V_FECHA
    RETURNING_VALUES EXIS_UNID_ALM, EXIS_COSTO_ALM;
    EXIS_UNID = EXIS_UNID + EXIS_UNID_ALM;
    EXIS_COSTO = EXIS_COSTO + EXIS_COSTO_ALM;
  END /* for */
END
