CREATE TABLE COBROS_X_DEPOSITAR_TRANSMITIDOS (
  ID INTEGER NOT NULL,
  UUID VARCHAR(100) CHARACTER SET NONE COLLATE NONE,
  DOCTO_CC_ID INTEGER,
  ABONO_TOTAL NUMERIC,   
  FECHA DATE);


ALTER TABLE COBROS_X_DEPOSITAR_TRANSMITIDOS ADD PRIMARY KEY (ID);


CREATE TRIGGER BI_COBROS_X_DEPOSITAR_TRANSMITIDOS_ID FOR COBROS_X_DEPOSITAR_TRANSMITIDOS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(COBROS_X_DEPOSITAR_TRANSMITIDOS_ID_GEN, 1);
END

