CREATE OR ALTER PROCEDURE ARTICULOS_MOBIL (FECHAINICIO DATE, FECHAFIN DATE)
RETURNS (
	ARTICULO_ID INTEGER,
	NOMBRE_ARTICULO VARCHAR(200),
	CODIGO_ARTICULO VARCHAR(20),
	CLAVE_ARTICULO VARCHAR(20),
	FACTOR_VENTA DOUBLE PRECISION,
	UNIDAD_VENTA VARCHAR(20),
	PORCENTAJE_IMPUESTO DOUBLE PRECISION,
	PRECIO DOUBLE PRECISION,
	DESCUENTO_PROMOCION DOUBLE PRECISION,
	PRECIO_NETO DOUBLE PRECISION,
	UNIDAD_MINIMA_VENTA DOUBLE PRECISION,
	PIEZAS_X_INNER DOUBLE PRECISION,
	PIEZAS_X_MASTER DOUBLE PRECISION,
	CODIGO_BARRAS VARCHAR(20),
	CODIGO_BARRAS_INNER VARCHAR(20),
	CODIGO_BARRAS_MASTER VARCHAR(20)
)
AS
DECLARE VARIABLE ROL_CLAVE_ART_ID INTEGER;
DECLARE VARIABLE NOMBRE_ROL VARCHAR(50);
DECLARE VARIABLE CLAVE_ARTICULO_GENERICO VARCHAR(20);

begin
    FOR SELECT
		A.ARTICULO_ID, A.NOMBRE, A.FACTOR_VENTA, A.UNIDAD_VENTA
		,I.PCTJE_IMPUESTO, PA.PRECIO, PA.PRECIO * (1 + (I.PCTJE_IMPUESTO / 100))
		FROM PRECIOS_EMPRESA PE
		INNER JOIN PRECIOS_ARTICULOS PA ON PA.PRECIO_EMPRESA_ID=PE.PRECIO_EMPRESA_ID
		INNER JOIN ARTICULOS A ON A.ARTICULO_ID=PA.ARTICULO_ID
		INNER JOIN IMPUESTOS_ARTICULOS IA ON IA.ARTICULO_ID=A.ARTICULO_ID
		INNER JOIN IMPUESTOS I ON IA.IMPUESTO_ID=I.IMPUESTO_ID		
		WHERE A.ESTATUS IN ('A','C') AND PE.NOMBRE LIKE '%Precio distribuidor%'
		ORDER BY A.ARTICULO_ID
    INTO :ARTICULO_ID, :NOMBRE_ARTICULO, :FACTOR_VENTA, :UNIDAD_VENTA, :PORCENTAJE_IMPUESTO, :PRECIO, :PRECIO_NETO DO
    BEGIN			    
		-- PROMOCIONES
		DESCUENTO_PROMOCION= 0.00;
		SELECT DPA.DESCUENTO FROM POLITICAS_DSCTOS_PROMOCION PDP
		INNER JOIN DSCTOS_PROMO_ARTS DPA ON PDP.POLITICA_DSCTO_PROMO_ID = DPA.POLITICA_DSCTO_PROMO_ID		
		WHERE DPA.ARTICULO_ID=:ARTICULO_ID AND PDP.FECHA_INI_VIGENCIA>=:FECHAINICIO AND PDP.FECHA_FIN_VIGENCIA<=:FECHAFIN AND PDP.HABILITADA='S'
		INTO :DESCUENTO_PROMOCION;
	
		IF (:DESCUENTO_PROMOCION IS NOT NULL)THEN
			PRECIO_NETO = :PRECIO_NETO * ( 1 - (:DESCUENTO_PROMOCION/100));
	    
		FOR SELECT RCA.ROL_CLAVE_ART_ID, RCA.NOMBRE, CA.CLAVE_ARTICULO FROM CLAVES_ARTICULOS CA
			INNER JOIN ROLES_CLAVES_ARTICULOS RCA ON RCA.ROL_CLAVE_ART_ID=CA.ROL_CLAVE_ART_ID
			WHERE CA.ARTICULO_ID = :ARTICULO_ID AND RCA.ROL_CLAVE_ART_ID IN (17,18, 11719, 11720, 11721)
			ORDER BY RCA.ROL_CLAVE_ART_ID
		INTO :ROL_CLAVE_ART_ID, :NOMBRE_ROL, :CLAVE_ARTICULO_GENERICO DO
		BEGIN
			IF (:ROL_CLAVE_ART_ID = 17) THEN
				CODIGO_ARTICULO = :CLAVE_ARTICULO_GENERICO;
			ELSE IF (:ROL_CLAVE_ART_ID = 18) THEN
				CLAVE_ARTICULO = :CLAVE_ARTICULO_GENERICO;
			ELSE IF (:ROL_CLAVE_ART_ID = 11719) THEN
				CODIGO_BARRAS = :CLAVE_ARTICULO_GENERICO;
			ELSE IF (:ROL_CLAVE_ART_ID = 11720) THEN
				CODIGO_BARRAS_INNER = :CLAVE_ARTICULO_GENERICO;
			ELSE IF (:ROL_CLAVE_ART_ID = 11721) THEN
				CODIGO_BARRAS_MASTER = :CLAVE_ARTICULO_GENERICO;
		END
		
		SELECT UNI_MIN_VENTA, CANTIDAD_INNER, MASTER FROM LIBRES_ARTICULOS
		WHERE ARTICULO_ID = :ARTICULO_ID
		INTO :UNIDAD_MINIMA_VENTA, :PIEZAS_X_INNER, :PIEZAS_X_MASTER;	
        
		SUSPEND;
    END
end
