CREATE TABLE CONFIGURACION_MOBIL (
	VIA_EMBARQUE_ID INTEGER,
	PRECIO_EMPRESA_ID INTEGER,
	CONCEPTO_CUENTA_X_COBRAR_ID INTEGER,
	CONDICION_PAGO_ID INTEGER,
	ROL_ART_CLAVE_PRINCIPAL_ID INTEGER,
	ROL_ART_CLAVE_ALTERNA_ID INTEGER,
	ROL_ART_CODIGO_BARRA_ID INTEGER,
	ROL_ART_CODIGO_BARRA_INNER_ID INTEGER,
	ROL_ART_CODIGO_BARRA_MASTER_ID INTEGER
);