CREATE TABLE CONFIGURACION_MOBIL (
	PRECIO_EMPRESA_ID INTEGER,
	CONCEPTO_CUENTA_X_COBRAR_ID INTEGER,
	CONDICION_PAGO_ID INTEGER,
	ROL_ART_CLAVE_PRINCIPAL_ID INTEGER,
	ROL_ART_CLAVE_ALTERNA_ID INTEGER,
	ROL_ART_CODIGO_BARRA_ID INTEGER,
	ROL_ART_CODIGO_BARRA_INNER_ID INTEGER,
	ROL_ART_CODIGO_BARRA_MASTER_ID INTEGER,
	MICROSIP_2020 INTEGER DEFAULT 0,
	SUCURSAL_ID INTEGER DEFAULT 0,        
        APPLY_POLITICA_PRECIO_CLIENTES INTEGER DEFAULT 0,
        COMPORTAMIENTO_CAPTURA VARCHAR(1),
        OPERA_DEPOSITOS INTEGER DEFAULT 0,
        TIPO_POLITICA_A_OPERAR VARCHAR(12),
        DIAS_HISTORIA INTEGER,
        FOLIO_FISCAL_ID INTEGER,--ES EL ID PARA EVITARME HACER UN QUERY VA LIGADO CON LA SERIE
        SERIE_CONCEPTO_CC VARCHAR(3)--SE USARA ESTA SERIE PARA GENERAR LA SERIE-FOLIO DEL DOCUMENTO FISCAL TOMANDO EN CUENTA EL CONCEPTO_CUENTA_X_COBRAR_ID, SUCURSAL_ID. TABLA FOLIOS_CONCEPTOS
);