CREATE OR ALTER PROCEDURE ARTICULOS_MOBIL (FECHAINICIO DATE, FECHAFIN DATE)
RETURNS (
	ARTICULO_ID INTEGER,
	NOMBRE_ARTICULO VARCHAR(200),
	CODIGO_ARTICULO VARCHAR(20),
	CLAVE_ARTICULO VARCHAR(20),
	FACTOR_VENTA DOUBLE PRECISION,
	UNIDAD_VENTA VARCHAR(20),
	PORCENTAJE_IVA DOUBLE PRECISION,
	PORCENTAJE_IEPS DOUBLE PRECISION,
	IMPUESTO_USAR VARCHAR(100),
	PRECIO DOUBLE PRECISION,
	DESCUENTO_PROMOCION DOUBLE PRECISION,
	PRECIO_NETO DOUBLE PRECISION,
	UNIDAD_MINIMA_VENTA DOUBLE PRECISION,
	PIEZAS_X_INNER DOUBLE PRECISION,
	PIEZAS_X_MASTER DOUBLE PRECISION,
	CODIGO_BARRAS VARCHAR(20),
	CODIGO_BARRAS_INNER VARCHAR(20),
	CODIGO_BARRAS_MASTER VARCHAR(20)
)
AS
DECLARE VARIABLE ROL_CLAVE_ART_ID INTEGER;
DECLARE VARIABLE NOMBRE_ROL VARCHAR(50);
DECLARE VARIABLE CLAVE_ARTICULO_GENERICO VARCHAR(20);
--VARIABLES TOMADAS DE LA CONFIGURACION
DECLARE VARIABLE PRECIO_EMPRESA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CLAVE_PRINCIPAL_ID INTEGER;
DECLARE VARIABLE ROL_ART_CLAVE_ALTERNA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_INNER_ID INTEGER;
DECLARE VARIABLE ROL_ART_CODIGO_BARRA_MASTER_ID INTEGER;

DECLARE VARIABLE APPLY_POLITICA_PRECIO_CLIENTES INTEGER;
DECLARE VARIABLE PORCENTAJE_DESC_PRECIO_CLIENTE DOUBLE PRECISION;

DECLARE VARIABLE PCTJE_IMPUESTO DOUBLE PRECISION;
DECLARE VARIABLE TIPO_IMPTO_ID INTEGER;
DECLARE VARIABLE NOMBRE_IMPUESTO VARCHAR(20); 
DECLARE VARIABLE TIPO VARCHAR(1);
DECLARE VARIABLE TOTAL_IMPUESTOS DOUBLE PRECISION;
BEGIN
    SELECT PRECIO_EMPRESA_ID, ROL_ART_CLAVE_PRINCIPAL_ID, ROL_ART_CLAVE_ALTERNA_ID, ROL_ART_CODIGO_BARRA_ID, 
    ROL_ART_CODIGO_BARRA_INNER_ID, ROL_ART_CODIGO_BARRA_MASTER_ID, APPLY_POLITICA_PRECIO_CLIENTES FROM CONFIGURACION_MOBIL
    INTO :PRECIO_EMPRESA_ID, :ROL_ART_CLAVE_PRINCIPAL_ID, :ROL_ART_CLAVE_ALTERNA_ID, :ROL_ART_CODIGO_BARRA_ID, 
    :ROL_ART_CODIGO_BARRA_INNER_ID, :ROL_ART_CODIGO_BARRA_MASTER_ID, :APPLY_POLITICA_PRECIO_CLIENTES;
   	
    IF (:APPLY_POLITICA_PRECIO_CLIENTES = 1)THEN
    BEGIN
        SELECT PDAC.DESCUENTO
        FROM POLITICAS_PRECIOS_CLIENTES C
	INNER JOIN POLITICAS_DSCTOS_ART_CLI PDAC ON C.politica_dscto_art_cli_id= PDAC.politica_dscto_art_cli_id		
	WHERE c.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID	
	INTO :PORCENTAJE_DESC_PRECIO_CLIENTE;
    END

    FOR SELECT A.ARTICULO_ID, A.NOMBRE, A.FACTOR_VENTA, A.UNIDAD_VENTA, PA.PRECIO
        FROM PRECIOS_EMPRESA PE
        INNER JOIN PRECIOS_ARTICULOS PA ON PA.PRECIO_EMPRESA_ID=PE.PRECIO_EMPRESA_ID
        INNER JOIN ARTICULOS A ON A.ARTICULO_ID=PA.ARTICULO_ID        
        WHERE A.ESTATUS IN ('A','C') AND PE.PRECIO_EMPRESA_ID = :PRECIO_EMPRESA_ID
        ORDER BY A.ARTICULO_ID
    INTO :ARTICULO_ID, :NOMBRE_ARTICULO, :FACTOR_VENTA, :UNIDAD_VENTA, :PRECIO DO
    BEGIN
	------------------REFACTOR IMPUESTOS
	TOTAL_IMPUESTOS = 0.00;
	PORCENTAJE_IVA = 0.00;
	PORCENTAJE_IEPS = 0.00;		
        IMPUESTO_USAR = 'SIN_IMPUESTO';
	FOR SELECT I.PCTJE_IMPUESTO, TI.TIPO_IMPTO_ID, TI.NOMBRE, TI.TIPO
        FROM IMPUESTOS I
        INNER JOIN TIPOS_IMPUESTOS TI ON TI.TIPO_IMPTO_ID = I.TIPO_IMPTO_ID
        INNER JOIN IMPUESTOS_ARTICULOS IA ON IA.IMPUESTO_ID = I.IMPUESTO_ID        
        INNER JOIN ARTICULOS A ON A.ARTICULO_ID = IA.ARTICULO_ID
        WHERE A.ARTICULO_ID = :ARTICULO_ID
        INTO :PCTJE_IMPUESTO, :TIPO_IMPTO_ID, :NOMBRE_IMPUESTO, :TIPO DO
        BEGIN	        
            IF (:TIPO_IMPTO_ID = 44) THEN--IVA
	    BEGIN
		TOTAL_IMPUESTOS = TOTAL_IMPUESTOS + (:PRECIO * (:PCTJE_IMPUESTO / 100));
		PORCENTAJE_IVA = :PCTJE_IMPUESTO;
	    END ELSE IF (:TIPO_IMPTO_ID = 45) THEN--IEPS
	    BEGIN
                TOTAL_IMPUESTOS = TOTAL_IMPUESTOS + (:PRECIO * (:PCTJE_IMPUESTO / 100));
	   	PORCENTAJE_IEPS = :PCTJE_IMPUESTO;
	    END		    		    		   
        END
        PRECIO_NETO = :PRECIO + TOTAL_IMPUESTOS;
       
       	IF ((PORCENTAJE_IVA > 0.00)AND(PORCENTAJE_IEPS > 0.00))THEN
            IMPUESTO_USAR = 'IVA_IEPS';
	ELSE IF ((PORCENTAJE_IVA > 0.00))THEN
            IMPUESTO_USAR = 'IVA';
	ELSE IF ((PORCENTAJE_IEPS > 0.00))THEN
            IMPUESTO_USAR = 'IEPS';
	------------------REFACTOR IMPUESTOS
	    	    	    	    	    	    
	IF (:APPLY_POLITICA_PRECIO_CLIENTES = 1)THEN
   	BEGIN	  
            IF (:PORCENTAJE_IVA <> 0)THEN
	    BEGIN
	   	:PRECIO_NETO = (:PRECIO - (:PRECIO * (:PORCENTAJE_DESC_PRECIO_CLIENTE / 100))) * (1 + (:PORCENTAJE_IVA / 100));
	   	:PRECIO = :PRECIO / (1 + (:PORCENTAJE_IVA / 100));
	    END
   	END	    	    	 
	    
        -- PROMOCIONES
        DESCUENTO_PROMOCION= 0.00;
        SELECT DPA.DESCUENTO FROM POLITICAS_DSCTOS_PROMOCION PDP
        INNER JOIN DSCTOS_PROMO_ARTS DPA ON PDP.POLITICA_DSCTO_PROMO_ID = DPA.POLITICA_DSCTO_PROMO_ID        
        WHERE DPA.ARTICULO_ID=:ARTICULO_ID AND PDP.FECHA_INI_VIGENCIA>=:FECHAINICIO AND PDP.FECHA_FIN_VIGENCIA<=:FECHAFIN AND PDP.HABILITADA='S'
        INTO :DESCUENTO_PROMOCION;
    
        IF (:DESCUENTO_PROMOCION IS NOT NULL)THEN
            PRECIO_NETO = :PRECIO_NETO * ( 1 - (:DESCUENTO_PROMOCION/100));
        
        CODIGO_ARTICULO = 'SIN_CODIGO';
        CLAVE_ARTICULO = 'SIN_CLAVE';
        CODIGO_BARRAS = 'SIN_CODIGO_BARRAS';
        CODIGO_BARRAS_INNER = 'SIN_CODIGO_INNER';
        CODIGO_BARRAS_MASTER = 'SIN_CODIGO_MASTER';
        FOR SELECT RCA.ROL_CLAVE_ART_ID, RCA.NOMBRE, CA.CLAVE_ARTICULO FROM CLAVES_ARTICULOS CA
            INNER JOIN ROLES_CLAVES_ARTICULOS RCA ON RCA.ROL_CLAVE_ART_ID=CA.ROL_CLAVE_ART_ID            
            WHERE CA.ARTICULO_ID = :ARTICULO_ID AND RCA.ROL_CLAVE_ART_ID IN (:ROL_ART_CLAVE_PRINCIPAL_ID,:ROL_ART_CLAVE_ALTERNA_ID, :ROL_ART_CODIGO_BARRA_ID, :ROL_ART_CODIGO_BARRA_INNER_ID, :ROL_ART_CODIGO_BARRA_MASTER_ID)
            ORDER BY RCA.ROL_CLAVE_ART_ID
        INTO :ROL_CLAVE_ART_ID, :NOMBRE_ROL, :CLAVE_ARTICULO_GENERICO DO
        BEGIN
            IF (:ROL_CLAVE_ART_ID = :ROL_ART_CLAVE_PRINCIPAL_ID) THEN        
                    CODIGO_ARTICULO = :CLAVE_ARTICULO_GENERICO;        
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CLAVE_ALTERNA_ID) THEN
                CLAVE_ARTICULO = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_ID) THEN
                CODIGO_BARRAS = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_INNER_ID) THEN
                CODIGO_BARRAS_INNER = :CLAVE_ARTICULO_GENERICO;
            ELSE IF (:ROL_CLAVE_ART_ID = :ROL_ART_CODIGO_BARRA_MASTER_ID) THEN
                CODIGO_BARRAS_MASTER = :CLAVE_ARTICULO_GENERICO;
        END
        
        SELECT UNI_MIN_VENTA, CANTIDAD_INNER, MASTER FROM LIBRES_ARTICULOS
        WHERE ARTICULO_ID = :ARTICULO_ID
        INTO :UNIDAD_MINIMA_VENTA, :PIEZAS_X_INNER, :PIEZAS_X_MASTER;    
        
        IF (:UNIDAD_MINIMA_VENTA IS NULL) THEN
            UNIDAD_MINIMA_VENTA = 0.00;
        IF (:PIEZAS_X_INNER IS NULL) THEN
            PIEZAS_X_INNER = 0.00;
        IF (:PIEZAS_X_MASTER IS NULL) THEN
            PIEZAS_X_MASTER = 0.00;
        
        SUSPEND;
    END
END